fixed CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -29,10 +29,12 @@ jobs:
         run: docker rm -f e-document-service
       - name: Run docker container
         run: |
+          set -e  # Exit immediately if a command exits with a non-zero status
           cd ~/e-document/  # แก้ไขให้ตรงกับ path ที่มี docker-compose.yml
           docker compose down              # หยุด container ที่รันอยู่
           docker compose pull              # ดึง image ล่าสุดจาก Docker Hub
           docker compose up -d             # รัน container ด้วย image ล่าสุด
+
 #        run: docker run -d -p 8088:8088 --name e-document-service acework2u/e-document-service:latest
 #        run: docker-compose -f docker-compose.prod.yml up -d
 #        run: docker buildx build --platform=linux/amd64 -t e-document-service . --target production -f Dockerfile.production --no-cache
